#As it is part of a buildroot project
#https://buildroot.org/downloads/manual/using-buildroot-toolchain.txt
#Prepare buildroot : make prepare-sdk or use BR2_PACKAGE_HOST_ENVIRONMENT_SETUP in your install (included on msk firmware

#source $pathtoyourbuildrootoutput/host/environment-setup


# --- Project Configuration ---
TARGET_BASE := dialogus
BIN_DIR     := bin
OBJ_DIR     := obj

# Mandatory Header Configuration
REG_H       := msk_top_regs.h
REG_URL     := https://raw.githubusercontent.com/OpenResearchInstitute/pluto_msk/refs/heads/main/rdl/outputs/c-header/msk_top_regs.h

# Compiler and Linker settings
CFLAGS   := -g -Wall -Wextra -O2
LDFLAGS  := -lpthread -liio -lm
CPPFLAGS := -MMD -MP

# --- Source Discovery ---
SOURCES := \
	config.c debug_printf.c debug_utils.c debugthread.c \
	dialogus.c fec.c frame_header.c iio_ops.c \
	interleaver.c msk_setup.c randomizer.c receiver.c \
	registers.c statistics.c timestamp.c tx_timeline.c \
	udp_encap.c udp_listener.c udp_socket.c

OBJS := $(patsubst %.c,$(OBJ_DIR)/%.o,$(SOURCES))
DEPS := $(patsubst %.c,$(OBJ_DIR)/%.d,$(SOURCES))

# --- Versioning Logic ---
GIT_DESCRIBE := $(shell git describe --tags --always --dirty --match "v*" 2>/dev/null || echo "v0.0.0-unknown")
GIT_CFLAGS   := -DDIALOGUS_VERSION=\"$(GIT_DESCRIBE)\"
TARGET_NAME  := $(TARGET_BASE)_$(GIT_DESCRIBE)
TARGET       := $(BIN_DIR)/$(TARGET_NAME)

# --- Build Rules ---

.PHONY: all clean help

all: $(TARGET)

# Rule to download mandatory header if missing
$(REG_H):
	@if ! command -v wget > /dev/null; then \
		echo "Error: $(REG_H) is missing and 'wget' is not installed."; \
		exit 1; \
	fi
	@echo "Mandatory file $(REG_H) missing. Downloading from $(REG_URL)..."
	wget -q $(REG_URL) -O $(REG_H) || (echo "Error: Download failed!"; exit 1)

# Link the final binary
$(TARGET): $(OBJS) | $(BIN_DIR)
	@echo "Linking: $@"
	$(CC) $(OBJS) -o $@ $(LDFLAGS)
	@ln -sf $(TARGET_NAME) $(BIN_DIR)/$(TARGET_BASE)
	@echo "Build complete. Latest binary linked at $(BIN_DIR)/$(TARGET_BASE)"

# Compile source files 
# Note: $(REG_H) added as a prerequisite so it downloads before any .c file compiles
$(OBJ_DIR)/%.o: %.c $(REG_H) | $(OBJ_DIR)
	@echo "Compiling: $<"
	$(CC) $(CFLAGS) $(CPPFLAGS) $(GIT_CFLAGS) -c $< -o $@

# Create directories if they don't exist
$(OBJ_DIR) $(BIN_DIR):
	mkdir -p $@

# Clean up build artifacts
clean:
	@echo "Cleaning up..."
	rm -rf $(OBJ_DIR) $(BIN_DIR)
	rm -f $(REG_H)

# Help target for users
help:
	@echo "Available targets:"
	@echo "  all    : Build the project (downloads $(REG_H) if missing)"
	@echo "  clean  : Remove objects and binaries"
	@echo "  help   : Show this help message"

# Include dependency files generated by -MMD
-include $(DEPS)
